CREATE TABLE users
(
    id    BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    email TEXT
        CONSTRAINT users_email_key UNIQUE NOT NULL,
    name  TEXT NOT NULL,
    password VARCHAR(72) NOT NULL
);
