// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	users "goads/internal/entities/users"

	mock "github.com/stretchr/testify/mock"
)

// Users is an autogenerated mock type for the Users type
type Users struct {
	mock.Mock
}

// ChangeEmail provides a mock function with given fields: ctx, id, email
func (_m *Users) ChangeEmail(ctx context.Context, id int64, email string) error {
	ret := _m.Called(ctx, id, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChangeName provides a mock function with given fields: ctx, id, name
func (_m *Users) ChangeName(ctx context.Context, id int64, name string) error {
	ret := _m.Called(ctx, id, name)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, email, name
func (_m *Users) Create(ctx context.Context, email string, name string) (users.User, error) {
	ret := _m.Called(ctx, email, name)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (users.User, error)); ok {
		return rf(ctx, email, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) users.User); ok {
		r0 = rf(ctx, email, name)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Users) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Users) GetByID(ctx context.Context, id int64) (users.User, error) {
	ret := _m.Called(ctx, id)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (users.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) users.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsers interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsers creates a new instance of Users. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsers(t mockConstructorTestingTNewUsers) *Users {
	mock := &Users{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
