// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"
	ads "goads/internal/entities/ads"

	entities "goads/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// AdsRepository is an autogenerated mock type for the AdsRepository type
type AdsRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AdsRepository) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *AdsRepository) GetByID(ctx context.Context, id int64) (ads.Ad, error) {
	ret := _m.Called(ctx, id)

	var r0 ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (ads.Ad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) ads.Ad); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(ads.Ad)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFiltered provides a mock function with given fields: ctx, filter
func (_m *AdsRepository) GetFiltered(ctx context.Context, filter entities.Filter) ([]ads.Ad, error) {
	ret := _m.Called(ctx, filter)

	var r0 []ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entities.Filter) ([]ads.Ad, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entities.Filter) []ads.Ad); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entities.Filter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNewID provides a mock function with given fields: ctx
func (_m *AdsRepository) GetNewID(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: ctx, ad
func (_m *AdsRepository) Store(ctx context.Context, ad ads.Ad) error {
	ret := _m.Called(ctx, ad)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ads.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, ad
func (_m *AdsRepository) Update(ctx context.Context, ad ads.Ad) error {
	ret := _m.Called(ctx, ad)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ads.Ad) error); ok {
		r0 = rf(ctx, ad)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewAdsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAdsRepository creates a new instance of AdsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAdsRepository(t mockConstructorTestingTNewAdsRepository) *AdsRepository {
	mock := &AdsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
