// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	users "goads/internal/entities/users"
)

// UsersGetter is an autogenerated mock type for the UsersGetter type
type UsersGetter struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UsersGetter) GetByID(ctx context.Context, id int64) (users.User, error) {
	ret := _m.Called(ctx, id)

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (users.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) users.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsersGetter interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsersGetter creates a new instance of UsersGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsersGetter(t mockConstructorTestingTNewUsersGetter) *UsersGetter {
	mock := &UsersGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
